### ISSUE TITLE
[NW] Free Farmfield Placement - Cattle Farm / Nandu Farm - wrong type and path

### ISSUE THREAD

**Issue by hiloyt** [Taludas/WholesomeHaciendaHaul#11]
Current:
Path="/Values/ModuleOwner/ModuleBuildRadius"
Type="merge"

Should be:
Path="/Values/ModuleOwner"
Type="add"

Something like this for assets.xml:

```
<!-- Animal Farms -->
  <ModOp Type="merge" GUID="1010267,1010269,1010263,101272,114456,114439,112676,112682" Path="/Values/ModuleOwner/ModuleBuildRadius" ModOpID="SetModuleRadiusVanillaAnimalFarms" Skip="1">
    <ModuleBuildRadius>15</ModuleBuildRadius>
  </ModOp>
  <ModOp Type="add" GUID="101269,5457" Path="/Values/ModuleOwner" ModOpID="SetModuleRadiusVanillaAnimalFarms" Skip="1">
    <ModuleBuildRadius>15</ModuleBuildRadius>
  </ModOp>
  <ImyaExpose Path="self::ModuleBuildRadius" ModOpID="SetModuleRadiusVanillaAnimalFarms" ExposeID="SetModuleRadiusVanillaAnimalFarms" Description="This Value sets the radius for all vanilla animal farms, in which you can build the field modules." Kind="Slider">
    <SliderDefinition Min="0" Max="250" Stepping="5" />
  </ImyaExpose>
```

**Comment by Taludas** [comment]
Thank you for the bug report! It is really appreciated and I already worked on it to resolve it.

For the next time you submit an issue on github, I want to give an advise to make it easier for the creator of the code. Your issue was very hard for me to work with in the first place, since you don't state what the actual issue is. You only provided the solution, which is really good, but if you don't communicate the problem first, I have to spent time on that. I needed 15 minutes to figure out what the problem was, before I could work on implementing your solution.
Nevertheless, thank you for pointing this bug out to me, I did a complete rewrite of the mod to make myself independend from the GUIDs of the farms. So in future if you use this mod, all vanilla and modded farms should be compatible form the start.

**Comment by hiloyt** [comment]
> Thank you for the bug report! It is really appreciated and I already worked on it to resolve it.
> 
> For the next time you submit an issue on github, I want to give an advise to make it easier for the creator of the code. Your issue was very hard for me to work with in the first place, since you don't state what the actual issue is. You only provided the solution, which is really good, but if you don't communicate the problem first, I have to spent time on that. I needed 15 minutes to figure out what the problem was, before I could work on implementing your solution. Nevertheless, thank you for pointing this bug out to me, I did a complete rewrite of the mod to make myself independend from the GUIDs of the farms. So in future if you use this mod, all vanilla and modded farms should be compatible form the start.

Thank you for so a fast fix! :)

And sorry for just pointing out the code instead of describing the problem. Bad behaviour from being a DevOps guy (and also submitting this issue a little too late, hah).
