### ISSUE TITLE
'Negative Attractiveness' reduction of custom Hacienda Policy 1 has odd interactions with the Hacienda Breweries

### ISSUE THREAD

**Issue by Tolverda** [Taludas/WholesomeHaciendaHaul#13]
Expected:  Breweries shouldn't be affected as it is now positive attractiveness
Actual:  Breweries attractiveness reduced from +5 to +1 when Hacienda Policy 1 is active

Thanks for the mod
Tol

**Comment by Taludas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Breweries with positive attractivness get a debuff instead of a buff from Hacienda Policy 1](https://trello.com/c/6lHjRqOW/18-breweries-with-positive-attractivness-get-a-debuff-instead-of-a-buff-from-hacienda-policy-1)

**Comment by Taludas** [comment]
I'm sorry, this problem is due to vanilla mechanics being what they are. The buff only works on reducing negative attractiveness. Therefore if you enter positive values for attractiveness it actually reduces it with the policies... So unfortunately nothing can be done (at least for now) to circumvent this issue
