### ISSUE TITLE
CTD while selecting policy with The True Jam Experience

### ISSUE THREAD

**Issue by Tosh94** [Taludas/WholesomeHaciendaHaul#16]
Hello Taludas,

I'm experiencing a crash to desktop when using the policy selection menu of the hacienda while the mod The True Jam Experience is active.

Setup:
* Anno 1800 GU 18 (Ubisoft Connect)
* Wholesome Hacienda Overhaul v2.2.2 (via iModYourAnno, no tweaks)
  * Pools and Definitions v7.0
* The True Jam Experience v1.0.4 (via iModYourAnno, no tweaks)
  * Info Description Parts v1.0.1
  * Products Extended v1.1.1

Steps to reproduce:
* Load up any save with a hacienda or build a new one (even creative mode works, this made testing so much easier)
* Open the UI, attempt to select a policy
* Rapidly scroll up and down a bunch (either scroll wheel or dragging the bar)
* CTD

This occurs only with this exact combination of mods, if either is missing, the CTD does not happen.

On a side note: the hacienda UI seems weird when scrolling the policies - the entire UI frame moves with the scroll bar until it reaches the bottom of the screen. This happens with just Wholesome Hacienda Overhaul as well.

**Comment by Taludas** [comment]
Hi, thank you for your report.

First of all: The issue with the Hacienda UI moving up and down while selecting and scrolling through the policies is a"vanilla" bug. Due to my way longer descriptions on the modded policies, the game does this. I can't circumwent it, apart from shortening the descriptions ofc xD. But that's not an option. Just scroll down after selecting a policy to fix the UI to the bottom where it belongs.

For the other part of your report, I can't reproduce it tbh. I loaded only the two mods in question, once from mod.io, ones manual install like you, exact same version as you, replicated the steps you took and nothing happens, everything works as expected.

Did you activate any other mod? 
Have you build up any settlement, or only the hacienda? Did you have a policy active? Or could you only select a policy?

Sometimes the Hacienda UI is bugging out in general... For example if you klick to fast after constructing a Hacienda module.

Let me know if there is more about it, I'll try too, and we'll see what comes from it.

As a sidenode: There should be nothing in the code I can influence, to make this bug happen in the first place. The two mods are not interacting in any way, so I don't know what might cause your issues. Also if you're playing in DX12 by chance, change back to DX11, as 12 always causes trouble...

**Comment by Tosh94** [comment]
Thanks for the fast reply!

I figured the moving UI was something you couldn't influence, but I wanted to make sure. I know the functionality is there, so it's not really an issue.

Regarding your remarks:
- I have reproduced the issue without activating any other mod. I did a bunch of testing to even find out which combination causes this crash as it first happened in a regular game when I had basically the full iModYourAnno library enabled - about 180 mods. I reduced them until I found the problematic combo.
- Whether I build a settlement or just have a hacienda made no difference, same result.
- I can select a policy if I do it without scrolling a lot, but the crash on rapid scrolling happens whether I have one active or not. 
- I've seen the buggy UI right after construction, too.
- I'm using DX11 as DX12 caused issues even in vanilla.

Not sure if that helps, but the very last batch of messages in the game log before the crash is
> [15:37:40][1956][    ERROR] rdsdk::CLogger::TraceLastError: Failed to open file data/modgraphics/models/jam_manufactory/factory_02.bfg failed with error 3: The system cannot find the path specified.
> 
> [15:37:40][1956][    ERROR] rdsdk::CLogger::TraceLastError: Failed to open file data/modgraphics/models/orchard_cherry/props/terrain_props/trees/cherry_tree_01.brp failed with error 3: The system cannot find the path specified.
> 
> [15:37:40][1956][    ERROR] rdsdk::CLogger::TraceLastError: Failed to open file data/modgraphics/models/orchard_cherry/props/terrain_props/trees/cherry_tree_02.brp failed with error 3: The system cannot find the path specified.
It's not just The True Jam Experience though as the error does not occur with that mod active while scrolling in the vanilla hacienda.

I'll try to see i a friend of mine can reproduce it on his end and come back to you. Maybe it's somehow system-specific.

**Comment by Tosh94** [comment]
Small Update: I've been able to reproduce the issue with just the Products Extended v1.1.1 shared mod. Same with a newer version of the same mod from Kurila. It does not occur with other shared product mods like the one from Jakob.

**Comment by Taludas** [comment]
Yet again, I justed the exact same versions of the mods (including the Products Extended Shared mod and didn't have the issue... Not really sure whats going on here tbh

**Comment by Tosh94** [comment]
I've gotten my friend to test the issue on his system and he can't reproduce it either. I've since reinstalled the game and mods and still have the issue, so it must be something with my system. :(
Sorry to have wasted your time, I guess this can be closed now.
