### ISSUE TITLE
Potential issue due to Hacienda mod

### ISSUE THREAD

**Issue by MadmanHS** [Taludas/WholesomeHaciendaHaul#4]
Hello Taludas,

first of all many thanks for your mod. I am facing some issues since GU15 as shown in the attached file. Certain Jornalero and Obrera demands suddenly double. As I am playing with many different mods, I am not sure which one causes it. Does anybody else face such issue after updating to GU15?

Best regards,
Maddy
![double demands](https://user-images.githubusercontent.com/90227088/191755675-ab472c52-2aa6-4dc6-a419-f625f059dfed.jpg)

**Comment by Taludas** [comment]
Hey Maddy,
thanks for your kind words! Glad you like it :)Concerning your bug report: Thank you for the precise description and screenshot. I am aware of the issue and working on a fix and update for GU15 right now. Unfortunately the GU butchered the whole balance with lifestyle goods and post, so I have to re-evaluate the mod balancing. I'm looking forward to finish this work by the weekend.
Kind regardsTaludas
 
 
  On Thu, 22 Sep 2022 at 15:10, ***@***.***> wrote:   


Hello Taludas,

first of all many thanks for your mod. I am facing some issues since GU15 as shown in the attached file. Certain Jornalero and Obrera demands suddenly double. As I am playing with many different mods, I am not sure which one causes it. Does anybody else face such issue after updating to GU15?

Best regards,
Maddy

**Comment by SirWaEvil** [comment]
i dissable overhaul bei lordys  all is fine for now

**Comment by MadmanHS** [comment]
Thanks Taludas for the quick answer! GU15 caused a lot of issues obviously. Also some of the lifestyle goods have strange names in my game. They have the names of the various house variants, like "many colors", "red roofs" etc. No idea what to fix for that...
Best wishes and again thanks for your mods

**Comment by Taludas** [comment]
This issue is now fixed in v1.4.0. Please update the mod files.

**Comment by MadmanHS** [comment]
Thanks Taludas! Works like a charm. Have a good day
